try {
    console.log('Normal');
    console.log(e);
    console.log('result');
} catch(e) {
    console.log('error');
}

console.log('Still normal');